"""노드 핸들러 레지스트리 — 모든 노드를 타입명으로 등록."""

from .data_nodes import (
    AugmentationNode,
    CSVLoaderNode,
    DataInspectorNode,
    ImageFolderNode,
    LabelEncoderNode,
    MinMaxScalerNode,
    NumpyInputNode,
    OneHotEncoderNode,
    PCANode,
    StandardScalerNode,
    TrainValSplitNode,
)
from .layer_nodes import (
    AddNode,
    BatchNormNode,
    ConcatNode,
    Conv1DLayerNode,
    Conv2DLayerNode,
    Conv2DTransposeNode,
    DenseLayerNode,
    DropoutNode,
    EmbeddingNode,
    FlattenNode,
    GlobalAveragePooling1DNode,
    GlobalAveragePooling2DNode,
    GRUNode,
    LSTMNode,
    MaxPooling2DNode,
    MultiHeadAttentionNode,
    PretrainedModelNode,
    ReshapeNode,
    TransformerBlockNode,
)
from .trainer_nodes import (
    EarlyStoppingNode,
    LossFunctionNode,
    LRSchedulerNode,
    ModelCheckpointNode,
    ModelSaveNode,
    OptimizerNode,
    TrainerNode,
)
from .model_io_nodes import (
    ModelLoaderNode,
    ModelTesterNode,
)
from .viz_nodes import (
    AccuracyCurveNode,
    ClassificationMetricsNode,
    ConfusionMatrixNode,
    CustomCodeNode,
    DataDistributionNode,
    FeatureMapViewerNode,
    GradCAMViewerNode,
    LossCurveNode,
    ModelSummaryNode,
    ONNXExportNode,
    PrecisionRecallCurveNode,
    PredictionViewerNode,
    RegressionMetricsNode,
    ROCCurveNode,
    TFLiteExportNode,
    tSNEViewerNode,
    UMAPViewerNode,
)

NODE_REGISTRY = {
    # ── 데이터 (11) ──────────────────────────────
    "CSVLoader": CSVLoaderNode(),
    "NumpyInput": NumpyInputNode(),
    "ImageFolder": ImageFolderNode(),
    "TrainValSplit": TrainValSplitNode(),
    "DataInspector": DataInspectorNode(),
    "StandardScaler": StandardScalerNode(),
    "MinMaxScaler": MinMaxScalerNode(),
    "LabelEncoder": LabelEncoderNode(),
    "OneHotEncoder": OneHotEncoderNode(),
    "PCA": PCANode(),
    "Augmentation": AugmentationNode(),
    # ── 레이어 (16) ──────────────────────────────
    "Dense": DenseLayerNode(),
    "Conv2D": Conv2DLayerNode(),
    "Conv1D": Conv1DLayerNode(),
    "Conv2DTranspose": Conv2DTransposeNode(),
    "MaxPooling2D": MaxPooling2DNode(),
    "Flatten": FlattenNode(),
    "GlobalAveragePooling2D": GlobalAveragePooling2DNode(),
    "GlobalAveragePooling1D": GlobalAveragePooling1DNode(),
    "BatchNorm": BatchNormNode(),
    "Dropout": DropoutNode(),
    "Embedding": EmbeddingNode(),
    "LSTM": LSTMNode(),
    "GRU": GRUNode(),
    "Reshape": ReshapeNode(),
    "Add": AddNode(),
    "Concat": ConcatNode(),
    "PretrainedModel": PretrainedModelNode(),
    "MultiHeadAttention": MultiHeadAttentionNode(),
    "TransformerBlock": TransformerBlockNode(),
    # ── 학습 (6) ─────────────────────────────────
    "Optimizer": OptimizerNode(),
    "LossFunction": LossFunctionNode(),
    "EarlyStopping": EarlyStoppingNode(),
    "ModelCheckpoint": ModelCheckpointNode(),
    "LRScheduler": LRSchedulerNode(),
    "Trainer": TrainerNode(),
    # ── 출력 (4) ─────────────────────────────────
    "ModelSave": ModelSaveNode(),
    "ModelLoader": ModelLoaderNode(),
    "ONNXExport": ONNXExportNode(),
    "TFLiteExport": TFLiteExportNode(),
    # ── 평가 (1) ──────────────────────────────────
    "ModelTester": ModelTesterNode(),
    # ── 시각화 / 평가 (12) ────────────────────────
    "LossCurve": LossCurveNode(),
    "AccuracyCurve": AccuracyCurveNode(),
    "ModelSummary": ModelSummaryNode(),
    "ClassificationMetrics": ClassificationMetricsNode(),
    "ConfusionMatrix": ConfusionMatrixNode(),
    "tSNEViewer": tSNEViewerNode(),
    "UMAPViewer": UMAPViewerNode(),
    "ROCCurve": ROCCurveNode(),
    "PrecisionRecallCurve": PrecisionRecallCurveNode(),
    "PredictionViewer": PredictionViewerNode(),
    "DataDistribution": DataDistributionNode(),
    "RegressionMetrics": RegressionMetricsNode(),
    "FeatureMapViewer": FeatureMapViewerNode(),
    "GradCAMViewer": GradCAMViewerNode(),
    # ── 기타 / 별칭 ─────────────────────────────
    "CustomCodeNode": CustomCodeNode(),
    # 예제 호환 별칭
    "Bidirectional LSTM": LSTMNode(),  # bidirectional=True가 기본
    "KFoldTrainer": TrainerNode(),  # K-Fold는 일반 Trainer로 대체
}
